version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: attendance-db
    ports:
      - "5603:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: attendance_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - attendance-net

  backend:
    build: ./Backend
    container_name: backend-service_2
    ports:
      - "3603:3603"
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_HOST: postgres
      DB_NAME: attendance_db
      DB_PORT: 5432
      PORT: 3603
    depends_on:
      - postgres
    networks:
      - attendance-net

  employee-attendance:
    build: ./Employee-Attendance
    container_name: employee-attendance-ui
    ports:
      - "8606:80"
    depends_on:
      - backend
    networks:
      - attendance-net

  hr-attendance:
    build: ./HR-Attendance
    container_name: hr-attendance-ui
    ports:
      - "8607:80"
    depends_on:
      - backend
    networks:
      - attendance-net

volumes:
  pgdata:

networks:
  attendance-net:

